package tw.taibunkesimi.lib.lomajichoanoann.unicode.choanoannsoantek

enum class ChoanoannSoantek {
    POJ_UNICODE_TO_POJ_INPUT,
    POJ_UNICODE_TO_KIP_INPUT,
    KIP_UNICODE_TO_KIP_INPUT,
    KIP_UNICODE_TO_POJ_INPUT,

    POJ_INPUT_TO_POJ_UNICODE,
    POJ_INPUT_TO_KIP_UNICODE,
    KIP_INPUT_TO_KIP_UNICODE,
    KIP_INPUT_TO_POJ_UNICODE,

    POJ_INPUT_TO_KIP_INPUT,
    KIP_INPUT_TO_POJ_INPUT,

    POJ_UNICODE_TO_KIP_UNICODE,
    KIP_UNICODE_TO_POJ_UNICODE
}
